// <auto-generated />
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MoviesDbContext))]
    partial class MoviesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Robert Downey Jr."
                        },
                        new
                        {
                            Id = 2,
                            Name = "Scarlett Johansson"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chris Evans"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tom Hardy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Natalie Portman"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Leonardo DiCaprio"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Jennifer Lawrence"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Brad Pitt"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Angelina Jolie"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Keanu Reeves"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Drama"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Horror"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sci-Fi"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreId = 2,
                            Title = "Movie 1"
                        },
                        new
                        {
                            Id = 2,
                            GenreId = 3,
                            Title = "Movie 2"
                        },
                        new
                        {
                            Id = 3,
                            GenreId = 4,
                            Title = "Movie 3"
                        },
                        new
                        {
                            Id = 4,
                            GenreId = 5,
                            Title = "Movie 4"
                        },
                        new
                        {
                            Id = 5,
                            GenreId = 1,
                            Title = "Movie 5"
                        },
                        new
                        {
                            Id = 6,
                            GenreId = 2,
                            Title = "Movie 6"
                        },
                        new
                        {
                            Id = 7,
                            GenreId = 3,
                            Title = "Movie 7"
                        },
                        new
                        {
                            Id = 8,
                            GenreId = 4,
                            Title = "Movie 8"
                        },
                        new
                        {
                            Id = 9,
                            GenreId = 5,
                            Title = "Movie 9"
                        },
                        new
                        {
                            Id = 10,
                            GenreId = 1,
                            Title = "Movie 10"
                        },
                        new
                        {
                            Id = 11,
                            GenreId = 2,
                            Title = "Movie 11"
                        },
                        new
                        {
                            Id = 12,
                            GenreId = 3,
                            Title = "Movie 12"
                        },
                        new
                        {
                            Id = 13,
                            GenreId = 4,
                            Title = "Movie 13"
                        },
                        new
                        {
                            Id = 14,
                            GenreId = 5,
                            Title = "Movie 14"
                        },
                        new
                        {
                            Id = 15,
                            GenreId = 1,
                            Title = "Movie 15"
                        },
                        new
                        {
                            Id = 16,
                            GenreId = 2,
                            Title = "Movie 16"
                        },
                        new
                        {
                            Id = 17,
                            GenreId = 3,
                            Title = "Movie 17"
                        },
                        new
                        {
                            Id = 18,
                            GenreId = 4,
                            Title = "Movie 18"
                        },
                        new
                        {
                            Id = 19,
                            GenreId = 5,
                            Title = "Movie 19"
                        },
                        new
                        {
                            Id = 20,
                            GenreId = 1,
                            Title = "Movie 20"
                        },
                        new
                        {
                            Id = 21,
                            GenreId = 2,
                            Title = "Movie 21"
                        },
                        new
                        {
                            Id = 22,
                            GenreId = 3,
                            Title = "Movie 22"
                        },
                        new
                        {
                            Id = 23,
                            GenreId = 4,
                            Title = "Movie 23"
                        },
                        new
                        {
                            Id = 24,
                            GenreId = 5,
                            Title = "Movie 24"
                        },
                        new
                        {
                            Id = 25,
                            GenreId = 1,
                            Title = "Movie 25"
                        },
                        new
                        {
                            Id = 26,
                            GenreId = 2,
                            Title = "Movie 26"
                        },
                        new
                        {
                            Id = 27,
                            GenreId = 3,
                            Title = "Movie 27"
                        },
                        new
                        {
                            Id = 28,
                            GenreId = 4,
                            Title = "Movie 28"
                        },
                        new
                        {
                            Id = 29,
                            GenreId = 5,
                            Title = "Movie 29"
                        },
                        new
                        {
                            Id = 30,
                            GenreId = 1,
                            Title = "Movie 30"
                        });
                });

            modelBuilder.Entity("Domain.Entities.MovieActor", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("MovieActors");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 1,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 1,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 2,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 2,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 2,
                            ActorId = 5
                        },
                        new
                        {
                            MovieId = 3,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 3,
                            ActorId = 5
                        },
                        new
                        {
                            MovieId = 3,
                            ActorId = 6
                        },
                        new
                        {
                            MovieId = 4,
                            ActorId = 5
                        },
                        new
                        {
                            MovieId = 4,
                            ActorId = 6
                        },
                        new
                        {
                            MovieId = 4,
                            ActorId = 7
                        },
                        new
                        {
                            MovieId = 5,
                            ActorId = 6
                        },
                        new
                        {
                            MovieId = 5,
                            ActorId = 7
                        },
                        new
                        {
                            MovieId = 5,
                            ActorId = 8
                        },
                        new
                        {
                            MovieId = 6,
                            ActorId = 7
                        },
                        new
                        {
                            MovieId = 6,
                            ActorId = 8
                        },
                        new
                        {
                            MovieId = 6,
                            ActorId = 9
                        },
                        new
                        {
                            MovieId = 7,
                            ActorId = 8
                        },
                        new
                        {
                            MovieId = 7,
                            ActorId = 9
                        },
                        new
                        {
                            MovieId = 7,
                            ActorId = 10
                        },
                        new
                        {
                            MovieId = 8,
                            ActorId = 9
                        },
                        new
                        {
                            MovieId = 8,
                            ActorId = 10
                        },
                        new
                        {
                            MovieId = 8,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 9,
                            ActorId = 10
                        },
                        new
                        {
                            MovieId = 9,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 9,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 10,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 10,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 10,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 11,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 11,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 11,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 12,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 12,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 12,
                            ActorId = 5
                        },
                        new
                        {
                            MovieId = 13,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 13,
                            ActorId = 5
                        },
                        new
                        {
                            MovieId = 13,
                            ActorId = 6
                        },
                        new
                        {
                            MovieId = 14,
                            ActorId = 5
                        },
                        new
                        {
                            MovieId = 14,
                            ActorId = 6
                        },
                        new
                        {
                            MovieId = 14,
                            ActorId = 7
                        },
                        new
                        {
                            MovieId = 15,
                            ActorId = 6
                        },
                        new
                        {
                            MovieId = 15,
                            ActorId = 7
                        },
                        new
                        {
                            MovieId = 15,
                            ActorId = 8
                        },
                        new
                        {
                            MovieId = 16,
                            ActorId = 7
                        },
                        new
                        {
                            MovieId = 16,
                            ActorId = 8
                        },
                        new
                        {
                            MovieId = 16,
                            ActorId = 9
                        },
                        new
                        {
                            MovieId = 17,
                            ActorId = 8
                        },
                        new
                        {
                            MovieId = 17,
                            ActorId = 9
                        },
                        new
                        {
                            MovieId = 17,
                            ActorId = 10
                        },
                        new
                        {
                            MovieId = 18,
                            ActorId = 9
                        },
                        new
                        {
                            MovieId = 18,
                            ActorId = 10
                        },
                        new
                        {
                            MovieId = 18,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 19,
                            ActorId = 10
                        },
                        new
                        {
                            MovieId = 19,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 19,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 20,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 20,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 20,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 21,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 21,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 21,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 22,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 22,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 22,
                            ActorId = 5
                        },
                        new
                        {
                            MovieId = 23,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 23,
                            ActorId = 5
                        },
                        new
                        {
                            MovieId = 23,
                            ActorId = 6
                        },
                        new
                        {
                            MovieId = 24,
                            ActorId = 5
                        },
                        new
                        {
                            MovieId = 24,
                            ActorId = 6
                        },
                        new
                        {
                            MovieId = 24,
                            ActorId = 7
                        },
                        new
                        {
                            MovieId = 25,
                            ActorId = 6
                        },
                        new
                        {
                            MovieId = 25,
                            ActorId = 7
                        },
                        new
                        {
                            MovieId = 25,
                            ActorId = 8
                        },
                        new
                        {
                            MovieId = 26,
                            ActorId = 7
                        },
                        new
                        {
                            MovieId = 26,
                            ActorId = 8
                        },
                        new
                        {
                            MovieId = 26,
                            ActorId = 9
                        },
                        new
                        {
                            MovieId = 27,
                            ActorId = 8
                        },
                        new
                        {
                            MovieId = 27,
                            ActorId = 9
                        },
                        new
                        {
                            MovieId = 27,
                            ActorId = 10
                        },
                        new
                        {
                            MovieId = 28,
                            ActorId = 9
                        },
                        new
                        {
                            MovieId = 28,
                            ActorId = 10
                        },
                        new
                        {
                            MovieId = 28,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 29,
                            ActorId = 10
                        },
                        new
                        {
                            MovieId = 29,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 29,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 30,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 30,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 30,
                            ActorId = 3
                        });
                });

            modelBuilder.Entity("Domain.Entities.MovieGenre", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MovieGenre");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 2,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 3,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 4,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 5,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 6,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 7,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 8,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 9,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 10,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 11,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 12,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 13,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 14,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 15,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 16,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 17,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 18,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 19,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 20,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 21,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 22,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 23,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 24,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 25,
                            GenreId = 1
                        },
                        new
                        {
                            MovieId = 26,
                            GenreId = 2
                        },
                        new
                        {
                            MovieId = 27,
                            GenreId = 3
                        },
                        new
                        {
                            MovieId = 28,
                            GenreId = 4
                        },
                        new
                        {
                            MovieId = 29,
                            GenreId = 5
                        },
                        new
                        {
                            MovieId = 30,
                            GenreId = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Movie", b =>
                {
                    b.HasOne("Domain.Entities.Genre", null)
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.MovieActor", b =>
                {
                    b.HasOne("Domain.Entities.Actor", "Actor")
                        .WithMany("MovieActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Domain.Entities.MovieGenre", b =>
                {
                    b.HasOne("Domain.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Domain.Entities.Actor", b =>
                {
                    b.Navigation("MovieActors");
                });

            modelBuilder.Entity("Domain.Entities.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("Domain.Entities.Movie", b =>
                {
                    b.Navigation("MovieActors");

                    b.Navigation("MovieGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
